language: bash
dist: trusty
sudo: false
addons:
  apt:
    packages:
    - haskell-platform
install:
- cabal update
- cabal install pandoc
before_script:
- export PATH=$PATH:/home/travis/.cabal/bin

script:
  - bash build.sh
