language: bash
dist: xenial
addons:
  apt:
    update: true
    packages:
    - pandoc

script:
  - pandoc --version
  - pandoc -t revealjs -s -o restful-apis.html restful-apis.md -V revealjs-url=https://revealjs.com -V transition=cube -V theme=sky -i
  - pandoc -t revealjs -s -o docs-as-code.html docs-as-code.md -V revealjs-url=https://revealjs.com -V transition=cube -V theme=sky -i
