language: bash
dist: xenial
addons:
  apt:
    update: true
    packages:
    - pandoc

script:
  - pandoc --version
  - pandoc -t revealjs -s -o $1.html $1 -V revealjs-url=https://revealjs.com -V transition=cube -V theme=sky -i
